### ISSUE TITLE
Darstellungsweise des Ergebnisses

### ISSUE THREAD

**Issue by lclassen** [kgoedde/BdK6.5.3_P3_SoSe2021_KATJA_GOEDDE#1]
Um die Darstellung des Ergebnisses zu verbessern und übersichtlicher zu machen, kann ein zusätzliches print mit Abtrennungszeichen in die for-Schleife eingebaut werden:
for pmid in pmids:
    full_url = base_url + pmid
    pm_json_data = urllib.request.urlopen(full_url).read()
    pm_data = json.loads(pm_json_data)
    title = pm_data["result"][pmid]["title"]
    pubdate = pm_data["result"][pmid]["pubdate"]
    print(title + pubdate)
    _print(-----------)_

**Comment by kgoedde** [comment]
Danke für den Verbesserungsvorschlag, habe es hinzugefügt! :-)
